/* eslint-disable */
/* This file is auto-generated by Convex - stub for type-checking */
import type { FunctionReference } from 'convex/server'

type QueryRef = FunctionReference<'query'>
type MutationRef = FunctionReference<'mutation'>
type ActionRef = FunctionReference<'action'>

export declare const api: {
  users: {
    getByEmail: QueryRef
    getById: QueryRef
    create: MutationRef
    update: MutationRef
  }
  sessions: {
    getByToken: QueryRef
    create: MutationRef
    remove: MutationRef
    removeByToken: MutationRef
  }
  accounts: {
    getByProviderAccountId: QueryRef
    listByUser: QueryRef
    create: MutationRef
    remove: MutationRef
  }
  conversations: {
    listByUser: QueryRef
    getById: QueryRef
    create: MutationRef
    update: MutationRef
    remove: MutationRef
  }
  messages: {
    listByConversation: QueryRef
    create: MutationRef
    remove: MutationRef
  }
  memories: {
    listByUser: QueryRef
    getById: QueryRef
    vectorSearch: ActionRef
    create: MutationRef
    remove: MutationRef
  }
  subscriptions: {
    getByUser: QueryRef
    create: MutationRef
    update: MutationRef
    cancel: MutationRef
  }
  tools: {
    listByUser: QueryRef
    create: MutationRef
    update: MutationRef
    remove: MutationRef
    toggle: MutationRef
  }
}
