/* eslint-disable */
/* This file is auto-generated by Convex - stub for type-checking */
import type { GenericId } from 'convex/values'

export type TableNames =
  | 'users'
  | 'sessions'
  | 'accounts'
  | 'verification'
  | 'conversations'
  | 'messages'
  | 'memories'
  | 'tools'
  | 'subscriptions'

export type Id<T extends TableNames> = GenericId<T>
