/* eslint-disable */
/* This file is auto-generated by Convex - stub for type-checking */
export {
  query,
  mutation,
  action,
  internalQuery,
  internalMutation,
  internalAction,
} from 'convex/server'
